gaea:
  mongodb:
    sys:
      host: localhost
      port: 27017
      user: tincery
      password: Txy123.com
      database: tincery_sys
    pro:
      host: localhost
      port: 27017
      user: tincery
      password: Txy123.com
      database: tincery_pro
  minio:
    host: localhost
    port: 9000
    username: admin
    password: 12345678
spring:
  application:
    name: src_test

  boot:
    admin:
      client:
        url: http://localhost:8111
        username: admin
        password: 123456
